my.greeting: Hello from config server

app:
    name: My App
    description: Welcome to ${app.name}


db:
    connection: "{connectionString: 'http://config', username: 'Config User', password: 'pass'}"
    host: 127.0.0.1
    port: 1200
